### ISSUE TITLE
Python Argument error

### ISSUE THREAD

**Issue by dsandstrom** [jugyo/SublimeRecentActiveFiles#1]
Sublime Text 2 / Linux

Running `recent_active_files` command results in:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./RecentActiveFiles.py", line 41, in run
Boost.Python.ArgumentError: Python argument types in
    Window.show_quick_panel(Window, list, function, int, int, function)
did not match C++ signature:
    show_quick_panel(SP<edit_window::reference>, boost::python::list, boost::python::api::object)
    show_quick_panel(SP<edit_window::reference>, boost::python::list, boost::python::api::object, unsigned int)
    show_quick_panel(SP<edit_window::reference>, boost::python::list, boost::python::api::object, unsigned int, int)
```

**Comment by dsandstrom** [comment]
Works fine with ST3.
